services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-node-api-dev
    ports:
      - "3001:3000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:18
    container_name: my-postgres-dev
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge
